import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

// ==================== API KEYS ====================
export const apiKeys = sqliteTable("api_keys", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(), // e.g., "Attio Production"
  service: text("service").notNull(), // "attio" | "klaviyo" | "calcom"
  encryptedKey: text("encrypted_key").notNull(),
  encryptedKeyIv: text("encrypted_key_iv").notNull(),
  keyHint: text("key_hint"), // Last 4 chars for display
  isValid: integer("is_valid", { mode: "boolean" }).default(true),
  lastTestedAt: integer("last_tested_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// ==================== WORKFLOWS ====================
export const workflows = sqliteTable("workflows", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  description: text("description"),

  // Trigger configuration
  triggerType: text("trigger_type").notNull(), // "webhook" | "manual" | "schedule"
  triggerConfig: text("trigger_config", { mode: "json" }).$type<{
    provider?: string;
    events?: string[];
    scheduleExpression?: string;
  }>(),
  webhookPath: text("webhook_path").unique(), // Unique path for webhook triggers
  webhookSecret: text("webhook_secret"), // For signature verification

  // Workflow code (generated by Claude)
  code: text("code"),
  requiredIntegrations: text("required_integrations", { mode: "json" }).$type<
    string[]
  >(),

  // Status
  isEnabled: integer("is_enabled", { mode: "boolean" }).default(false),
  status: text("status").default("draft"), // "draft" | "active" | "paused" | "error"

  // Stats
  totalExecutions: integer("total_executions").default(0),
  successfulExecutions: integer("successful_executions").default(0),
  failedExecutions: integer("failed_executions").default(0),
  lastExecutedAt: integer("last_executed_at", { mode: "timestamp" }),

  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// ==================== EXECUTION LOGS ====================
export const executionLogs = sqliteTable("execution_logs", {
  id: text("id").primaryKey(),
  workflowId: text("workflow_id")
    .notNull()
    .references(() => workflows.id, { onDelete: "cascade" }),

  status: text("status").notNull(), // "pending" | "running" | "success" | "failed"
  triggerType: text("trigger_type").notNull(), // "webhook" | "manual" | "schedule"

  inputPayload: text("input_payload", { mode: "json" }).$type<
    Record<string, unknown>
  >(),
  outputPayload: text("output_payload", { mode: "json" }).$type<
    Record<string, unknown>
  >(),

  errorMessage: text("error_message"),
  errorStack: text("error_stack"),

  stepLogs: text("step_logs", { mode: "json" }).$type<
    Array<{
      name: string;
      status: "success" | "failed" | "skipped";
      input?: unknown;
      output?: unknown;
      error?: string;
      durationMs: number;
      timestamp: string;
    }>
  >(),

  startedAt: integer("started_at", { mode: "timestamp" }).notNull(),
  completedAt: integer("completed_at", { mode: "timestamp" }),
  durationMs: integer("duration_ms"),
});

// ==================== EMAIL LOGS ====================
export const emailLogs = sqliteTable("email_logs", {
  id: text("id").primaryKey(),

  // Email-Details
  emailType: text("email_type").notNull(), // "confirmation" | "reminder_24h" | "reminder_1h" | "no_show" | "meeting_running" | "thank_you_discovery" | "thank_you_strategie" | "test"
  to: text("to").notNull(),
  subject: text("subject").notNull(),
  from: text("from").notNull(),
  htmlContent: text("html_content"), // Full HTML content of the email

  // Status
  status: text("status").notNull(), // "sent" | "failed" | "scheduled"
  resendId: text("resend_id"), // Resend API response ID
  errorMessage: text("error_message"),

  // Referenzen (optional)
  bookingId: text("booking_id"),
  userId: text("user_id").notNull(),

  // Timestamps
  sentAt: integer("sent_at", { mode: "timestamp" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
});

// ==================== BOOKINGS ====================
export const bookings = sqliteTable("bookings", {
  id: text("id").primaryKey(),

  // Booking details
  email: text("email").notNull(),
  firstName: text("first_name"),
  lastName: text("last_name"),
  phone: text("phone"),

  // Appointment details
  startTime: integer("start_time", { mode: "timestamp" }).notNull(),
  endTime: integer("end_time", { mode: "timestamp" }),
  meetingLink: text("meeting_link"),
  eventType: text("event_type"), // e.g., "Discovery Call"

  // Cal.com reference
  calcomBookingId: text("calcom_booking_id"),
  calcomEventUid: text("calcom_event_uid"),

  // Reminder tracking
  confirmationSentAt: integer("confirmation_sent_at", { mode: "timestamp" }),
  reminder24hSentAt: integer("reminder_24h_sent_at", { mode: "timestamp" }),
  reminder1hSentAt: integer("reminder_1h_sent_at", { mode: "timestamp" }),

  // Status
  status: text("status").default("confirmed"), // "confirmed" | "cancelled" | "completed"

  // User reference (who owns this workflow)
  userId: text("user_id").notNull(),
  workflowId: text("workflow_id").references(() => workflows.id, { onDelete: "set null" }),

  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// ==================== RELATIONS ====================
export const workflowsRelations = relations(workflows, ({ many }) => ({
  executionLogs: many(executionLogs),
  bookings: many(bookings),
}));

export const executionLogsRelations = relations(executionLogs, ({ one }) => ({
  workflow: one(workflows, {
    fields: [executionLogs.workflowId],
    references: [workflows.id],
  }),
}));

export const bookingsRelations = relations(bookings, ({ one }) => ({
  workflow: one(workflows, {
    fields: [bookings.workflowId],
    references: [workflows.id],
  }),
}));

// ==================== TYPES ====================
export type ApiKey = typeof apiKeys.$inferSelect;
export type NewApiKey = typeof apiKeys.$inferInsert;

export type Workflow = typeof workflows.$inferSelect;
export type NewWorkflow = typeof workflows.$inferInsert;

export type ExecutionLog = typeof executionLogs.$inferSelect;
export type NewExecutionLog = typeof executionLogs.$inferInsert;

export type Booking = typeof bookings.$inferSelect;
export type NewBooking = typeof bookings.$inferInsert;

export type EmailLog = typeof emailLogs.$inferSelect;
export type NewEmailLog = typeof emailLogs.$inferInsert;
